---
name: Test Gocpp Module
on: push
jobs:
  mac-test-module:
    name: Mac Test Module
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prereqs
        run: brew install swig

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Generate library file
        run: ./gen_lib

      - name: Run tests
        run: go test -v

  ubuntu-test-module:
    name: Ubuntu Test Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prereqs
        run: sudo apt install -y swig g++

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Generate library file
        run: ./gen_lib

      - name: Run tests
        run: go test -v
